// This file is auto-generated by @hey-api/openapi-ts

export type IczpNet_AbpCommons_Models_FilterInput = {
    propertyNameId?: string;
    expressType?: (string) | null;
    value: string;
};

export type IczpNet_AbpCommons_Models_ValueInput = {
    value: string;
};

export type IczpNet_Invoicing_Brands_Dtos_BrandCreateInput = {
    name: string;
    picture?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_Brands_Dtos_BrandDetailDto = {
    id?: string;
    name?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_Brands_Dtos_BrandDto = {
    id?: string;
    name?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_Brands_Dtos_BrandSampleDto = {
    id?: string;
    name?: (string) | null;
    picture?: (string) | null;
};

export type IczpNet_Invoicing_Brands_Dtos_BrandSetProductTypeInput = {
    brandId?: string;
    productTypeIdList?: Array<(string)> | null;
};

export type IczpNet_Invoicing_Brands_Dtos_BrandUpdateInput = {
    name: string;
    picture?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_Enums_ValueTypeEnum = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export type IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryCreateInput = {
    parentId?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    isActive?: boolean;
    sorting?: number;
    description?: (string) | null;
    shopId?: (string) | null;
};

export type IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDetailDto = {
    id?: string;
    parentId?: (string) | null;
    name?: (string) | null;
    depth?: number;
    childrenCount?: number;
    fullPath?: (string) | null;
    fullPathName?: (string) | null;
    code?: (string) | null;
    sorting?: number;
    isStatic?: boolean;
    isActive?: boolean;
    shopId?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDto = {
    id?: string;
    parentId?: (string) | null;
    name?: (string) | null;
    depth?: number;
    childrenCount?: number;
    fullPath?: (string) | null;
    fullPathName?: (string) | null;
    code?: (string) | null;
    sorting?: number;
    isStatic?: boolean;
    isActive?: boolean;
    shopId?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryUpdateInput = {
    parentId?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    isActive?: boolean;
    sorting?: number;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductCategorys_ProductCategoryInfo = {
    id?: string;
    parentId?: (string) | null;
    name?: (string) | null;
    depth?: number;
    childrenCount?: number;
    fullPath?: (string) | null;
    fullPathName?: (string) | null;
    code?: (string) | null;
    sorting?: number;
    isStatic?: boolean;
    isActive?: boolean;
    shopId?: (string) | null;
};

export type IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryCreateInput = {
    parentId?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    isActive?: boolean;
    sorting?: number;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDetailDto = {
    id?: string;
    parentId?: (string) | null;
    name?: (string) | null;
    depth?: number;
    childrenCount?: number;
    fullPath?: (string) | null;
    fullPathName?: (string) | null;
    code?: (string) | null;
    sorting?: number;
    isStatic?: boolean;
    isActive?: boolean;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDto = {
    id?: string;
    parentId?: (string) | null;
    name?: (string) | null;
    depth?: number;
    childrenCount?: number;
    fullPath?: (string) | null;
    fullPathName?: (string) | null;
    code?: (string) | null;
    sorting?: number;
    isStatic?: boolean;
    isActive?: boolean;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryUpdateInput = {
    parentId?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    isActive?: boolean;
    sorting?: number;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductTypeCategorys_ProductTypeCategoryInfo = {
    id?: string;
    parentId?: (string) | null;
    name?: (string) | null;
    depth?: number;
    childrenCount?: number;
    fullPath?: (string) | null;
    fullPathName?: (string) | null;
    code?: (string) | null;
    sorting?: number;
    isStatic?: boolean;
    isActive?: boolean;
};

export type IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeCreateInput = {
    productTypeCategoryId?: (string) | null;
    name: string;
    picture?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDetailDto = {
    id?: string;
    name?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDto = {
    id?: string;
    name?: (string) | null;
    picture?: (string) | null;
    productTypeCategoryId?: (string) | null;
    spuCount?: number;
};

export type IczpNet_Invoicing_ProductTypes_Dtos_ProductTypePropertyNameDto = {
    propertyName?: IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameSampleDto;
    isUnique?: boolean;
    isRequired?: boolean;
    isHidden?: boolean;
    isMultipleValue?: boolean;
    isCustomerPlus?: boolean;
    isValidateValue?: boolean;
    isValidateCount?: boolean;
    isValidateLength?: boolean;
    isValidateRegex?: boolean;
    isFormat?: boolean;
    defaultValue?: (string) | null;
    placeholder?: boolean;
    explain?: boolean;
    minValue?: (string) | null;
    maxValue?: (string) | null;
    minCount?: (number) | null;
    maxCount?: (number) | null;
    maxLength?: (number) | null;
    minLength?: (number) | null;
    formatInput?: (string) | null;
    formatOutput?: (string) | null;
    sorting?: number;
};

export type IczpNet_Invoicing_ProductTypes_Dtos_ProductTypePropertyNameInput = {
    isUnique?: boolean;
    isRequired?: boolean;
    isHidden?: boolean;
    isMultipleValue?: boolean;
    isCustomerPlus?: boolean;
    isValidateValue?: boolean;
    isValidateCount?: boolean;
    isValidateLength?: boolean;
    isValidateRegex?: boolean;
    isFormat?: boolean;
    defaultValue?: (string) | null;
    placeholder?: boolean;
    explain?: boolean;
    minValue?: (string) | null;
    maxValue?: (string) | null;
    minCount?: (number) | null;
    maxCount?: (number) | null;
    maxLength?: (number) | null;
    minLength?: (number) | null;
    formatInput?: (string) | null;
    formatOutput?: (string) | null;
    sorting?: number;
};

export type IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeUpdateInput = {
    productTypeCategoryId?: (string) | null;
    name: string;
    picture?: (string) | null;
    description?: (string) | null;
};

export type IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameCreateInput = {
    name?: (string) | null;
    code?: (string) | null;
    unit?: (string) | null;
    valueType?: IczpNet_Invoicing_Enums_ValueTypeEnum;
};

export type IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameDto = {
    id?: string;
    name?: (string) | null;
    code?: (string) | null;
    unit?: (string) | null;
    valueType?: IczpNet_Invoicing_Enums_ValueTypeEnum;
};

export type IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameSampleDto = {
    id?: string;
    name?: (string) | null;
    valueType?: IczpNet_Invoicing_Enums_ValueTypeEnum;
};

export type IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameUpdateInput = {
    name?: (string) | null;
    code?: (string) | null;
    unit?: (string) | null;
};

export type IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueCreateInput = {
    propertyNameId?: string;
    displayValue?: (string) | null;
};

export type IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueDto = {
    id?: string;
    displayValue?: (string) | null;
    standardProductUnitApplyCount?: number;
};

export type IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueUpdateInput = {
    id?: string;
    displayValue?: (string) | null;
};

export type IczpNet_Invoicing_SalePropertys_Dtos_SalePropertyDto = {
    id?: (string) | null;
    name?: (string) | null;
    saleValueList?: Array<IczpNet_Invoicing_SaleValues_Dtos_SaleValueDto> | null;
};

export type IczpNet_Invoicing_SaleValues_Dtos_SaleValueDto = {
    id?: (string) | null;
    value?: (string) | null;
};

export type IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitCreateInput = {
    brandId?: (string) | null;
    title?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
    propertyValues?: {
        [key: string]: (Array<IczpNet_AbpCommons_Models_ValueInput> | null);
    } | null;
    categoryIdList?: Array<(string)> | null;
    salePropertyList?: Array<IczpNet_Invoicing_SalePropertys_Dtos_SalePropertyDto> | null;
    stockKeepingUnitList?: Array<IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitCreateOrUpdateInput> | null;
    productTypeId?: string;
};

export type IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDetailDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    title?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    concurrencyStamp?: (string) | null;
    brand?: IczpNet_Invoicing_Brands_Dtos_BrandSampleDto;
    isActive?: boolean;
    price?: (number) | null;
    minPrice?: (number) | null;
    maxPrice?: (number) | null;
    description?: (string) | null;
    propertyValues?: {
        [key: string]: (Array<IczpNet_AbpCommons_Models_ValueInput> | null);
    } | null;
    stockKeepingUnitList?: Array<IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDetailDto> | null;
    salePropertyList?: Array<IczpNet_Invoicing_SalePropertys_Dtos_SalePropertyDto> | null;
    categoryIdList?: Array<(string)> | null;
};

export type IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    title?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    concurrencyStamp?: (string) | null;
    propertyValues?: {
        [key: string]: (Array<IczpNet_AbpCommons_Models_ValueInput> | null);
    } | null;
    isActive?: boolean;
    price?: (number) | null;
    minPrice?: (number) | null;
    maxPrice?: (number) | null;
};

export type IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitUpdateInput = {
    brandId?: (string) | null;
    title?: (string) | null;
    name?: (string) | null;
    code?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
    propertyValues?: {
        [key: string]: (Array<IczpNet_AbpCommons_Models_ValueInput> | null);
    } | null;
    categoryIdList?: Array<(string)> | null;
    salePropertyList?: Array<IczpNet_Invoicing_SalePropertys_Dtos_SalePropertyDto> | null;
    stockKeepingUnitList?: Array<IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitCreateOrUpdateInput> | null;
};

export type IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitCreateInput = {
    title?: (string) | null;
    code?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
    inventoryQuantity?: number;
    price?: number;
    isActive?: boolean;
    saleValueIndex?: {
        [key: string]: (number);
    } | null;
    standardProductUnitId?: string;
};

export type IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitCreateOrUpdateInput = {
    title?: (string) | null;
    code?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
    inventoryQuantity?: number;
    price?: number;
    isActive?: boolean;
    saleValueIndex?: {
        [key: string]: (number);
    } | null;
    id?: (string) | null;
};

export type IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDetailDto = {
    id?: string;
    title?: (string) | null;
    code?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
    totalStockQuantity?: number;
    lockStockQuantity?: number;
    stockQuantity?: number;
    price?: number;
    isActive?: boolean;
    saleValueIndex?: {
        [key: string]: (number);
    } | null;
};

export type IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDto = {
    id?: string;
    title?: (string) | null;
    code?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
    totalStockQuantity?: number;
    lockStockQuantity?: number;
    stockQuantity?: number;
    price?: number;
    isActive?: boolean;
};

export type IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitUpdateInput = {
    title?: (string) | null;
    code?: (string) | null;
    picture?: (string) | null;
    description?: (string) | null;
    inventoryQuantity?: number;
    price?: number;
    isActive?: boolean;
    saleValueIndex?: {
        [key: string]: (number);
    } | null;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_Brands_Dtos_BrandDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_Brands_Dtos_BrandDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_ProductCategorys_ProductCategoryInfo__IczpNet_Invoicing_Domain_Shared__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_ProductCategorys_ProductCategoryInfo> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_ProductTypeCategorys_ProductTypeCategoryInfo__IczpNet_Invoicing_Domain_Shared__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_ProductTypeCategorys_ProductTypeCategoryInfo> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDto__IczpNet_Invoicing_Application_Contracts__Version_9_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDto> | null;
    totalCount?: number;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto = {
    grantedPolicies?: {
        [key: string]: (boolean);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto = {
    localization?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto;
    auth?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto;
    setting?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto;
    currentUser?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto;
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto;
    currentTenant?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto;
    timing?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto;
    clock?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto;
    objectExtensions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto;
    extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto = {
    enabledFeatures?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto = {
    values?: {
        [key: string]: {
            [key: string]: (string);
        };
    } | null;
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    languages?: Array<Volo_Abp_Localization_LanguageInfo> | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
    defaultResourceName?: (string) | null;
    languagesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
    languageFilesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto = {
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto = {
    texts?: {
        [key: string]: (string);
    } | null;
    baseResources?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto = {
    kind?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto = {
    displayName?: (string) | null;
    englishName?: (string) | null;
    threeLetterIsoLanguageName?: (string) | null;
    twoLetterIsoLanguageName?: (string) | null;
    isRightToLeft?: boolean;
    cultureName?: (string) | null;
    name?: (string) | null;
    nativeName?: (string) | null;
    dateTimeFormat?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto = {
    isAuthenticated?: boolean;
    id?: (string) | null;
    tenantId?: (string) | null;
    impersonatorUserId?: (string) | null;
    impersonatorTenantId?: (string) | null;
    impersonatorUserName?: (string) | null;
    impersonatorTenantName?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surName?: (string) | null;
    email?: (string) | null;
    emailVerified?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberVerified?: boolean;
    roles?: Array<(string)> | null;
    sessionId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto = {
    calendarAlgorithmType?: (string) | null;
    dateTimeFormatLong?: (string) | null;
    shortDatePattern?: (string) | null;
    fullDateTimePattern?: (string) | null;
    dateSeparator?: (string) | null;
    shortTimePattern?: (string) | null;
    longTimePattern?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone = {
    timeZoneName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto = {
    properties?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto = {
    fields?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto> | null;
    localizationResource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto = {
    name?: (string) | null;
    value?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto = {
    onGet?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto;
    onCreate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto;
    onUpdate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto = {
    typeSimple?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto = {
    type?: (string) | null;
    typeSimple?: (string) | null;
    displayName?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto;
    api?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto;
    ui?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto;
    policy?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPolicyDto;
    attributes?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto> | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
    defaultValue?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyFeaturePolicyDto = {
    features?: Array<(string)> | null;
    requiresAll?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyGlobalFeaturePolicyDto = {
    features?: Array<(string)> | null;
    requiresAll?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPermissionPolicyDto = {
    permissionNames?: Array<(string)> | null;
    requiresAll?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPolicyDto = {
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyGlobalFeaturePolicyDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyFeaturePolicyDto;
    permissions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPermissionPolicyDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto = {
    onTable?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto;
    onCreateForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    onEditForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    lookup?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto = {
    url?: (string) | null;
    resultListPropertyName?: (string) | null;
    displayPropertyName?: (string) | null;
    valuePropertyName?: (string) | null;
    filterParamName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto = {
    name?: (string) | null;
    resource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto = {
    entities?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto = {
    modules?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto;
    } | null;
    enums?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone = {
    iana?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone;
    windows?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto = {
    timeZone?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone = {
    timeZoneId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto = {
    id?: (string) | null;
    name?: (string) | null;
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto = {
    success?: boolean;
    tenantId?: (string) | null;
    name?: (string) | null;
    normalizedName?: (string) | null;
    isActive?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto = {
    isEnabled?: boolean;
};

export type Volo_Abp_Http_Modeling_ActionApiDescriptionModel = {
    uniqueName?: (string) | null;
    name?: (string) | null;
    httpMethod?: (string) | null;
    url?: (string) | null;
    supportedVersions?: Array<(string)> | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    parameters?: Array<Volo_Abp_Http_Modeling_ParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
    allowAnonymous?: (boolean) | null;
    implementFrom?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel = {
    modules?: {
        [key: string]: Volo_Abp_Http_Modeling_ModuleApiDescriptionModel;
    } | null;
    types?: {
        [key: string]: Volo_Abp_Http_Modeling_TypeApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerApiDescriptionModel = {
    controllerName?: (string) | null;
    controllerGroupName?: (string) | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: (string) | null;
    type?: (string) | null;
    interfaces?: Array<Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel> | null;
    actions?: {
        [key: string]: Volo_Abp_Http_Modeling_ActionApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel = {
    type?: (string) | null;
    name?: (string) | null;
    methods?: Array<Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel> | null;
};

export type Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel = {
    name?: (string) | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
};

export type Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel = {
    name?: (string) | null;
    typeAsString?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
};

export type Volo_Abp_Http_Modeling_ModuleApiDescriptionModel = {
    rootPath?: (string) | null;
    remoteServiceName?: (string) | null;
    controllers?: {
        [key: string]: Volo_Abp_Http_Modeling_ControllerApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ParameterApiDescriptionModel = {
    nameOnMethod?: (string) | null;
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
    constraintTypes?: Array<(string)> | null;
    bindingSourceId?: (string) | null;
    descriptorName?: (string) | null;
};

export type Volo_Abp_Http_Modeling_PropertyApiDescriptionModel = {
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isRequired?: boolean;
    minLength?: (number) | null;
    maxLength?: (number) | null;
    minimum?: (string) | null;
    maximum?: (string) | null;
    regex?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel = {
    type?: (string) | null;
    typeSimple?: (string) | null;
};

export type Volo_Abp_Http_Modeling_TypeApiDescriptionModel = {
    baseType?: (string) | null;
    isEnum?: boolean;
    enumNames?: Array<(string)> | null;
    enumValues?: Array<unknown> | null;
    genericArguments?: Array<(string)> | null;
    properties?: Array<Volo_Abp_Http_Modeling_PropertyApiDescriptionModel> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorInfo = {
    code?: (string) | null;
    message?: (string) | null;
    details?: (string) | null;
    data?: {
        [key: string]: unknown;
    } | null;
    validationErrors?: Array<Volo_Abp_Http_RemoteServiceValidationErrorInfo> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorResponse = {
    error?: Volo_Abp_Http_RemoteServiceErrorInfo;
};

export type Volo_Abp_Http_RemoteServiceValidationErrorInfo = {
    message?: (string) | null;
    members?: Array<(string)> | null;
};

export type Volo_Abp_Localization_LanguageInfo = {
    cultureName?: (string) | null;
    uiCultureName?: (string) | null;
    displayName?: (string) | null;
    readonly twoLetterISOLanguageName?: (string) | null;
};

export type Volo_Abp_NameValue = {
    name?: (string) | null;
    value?: (string) | null;
};

export type GetApiAbpApiDefinitionData = {
    query?: {
        IncludeTypes?: boolean;
    };
};

export type GetApiAbpApiDefinitionResponse = (Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel);

export type GetApiAbpApiDefinitionError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpApplicationConfigurationData = {
    query?: {
        IncludeLocalizationResources?: boolean;
    };
};

export type GetApiAbpApplicationConfigurationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto);

export type GetApiAbpApplicationConfigurationError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpApplicationLocalizationData = {
    query: {
        CultureName: string;
        OnlyDynamics?: boolean;
    };
};

export type GetApiAbpApplicationLocalizationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto);

export type GetApiAbpApplicationLocalizationError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpMultiTenancyTenantsByNameByNameData = {
    path: {
        name: string;
    };
};

export type GetApiAbpMultiTenancyTenantsByNameByNameResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type GetApiAbpMultiTenancyTenantsByNameByNameError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpMultiTenancyTenantsByIdByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAbpMultiTenancyTenantsByIdByIdResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type GetApiAbpMultiTenancyTenantsByIdByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppBrandData = {
    body?: IczpNet_Invoicing_Brands_Dtos_BrandCreateInput;
};

export type PostApiAppBrandResponse = (IczpNet_Invoicing_Brands_Dtos_BrandDetailDto);

export type PostApiAppBrandError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppBrandData = {
    query?: {
        Keyword?: string;
        MaxResultCount?: number;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppBrandResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppBrandError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiAppBrandByIdData = {
    body?: IczpNet_Invoicing_Brands_Dtos_BrandUpdateInput;
    path: {
        id: string;
    };
};

export type PutApiAppBrandByIdResponse = (IczpNet_Invoicing_Brands_Dtos_BrandDetailDto);

export type PutApiAppBrandByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppBrandByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppBrandByIdResponse = (IczpNet_Invoicing_Brands_Dtos_BrandDetailDto);

export type GetApiAppBrandByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppBrandByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppBrandByIdResponse = (unknown);

export type DeleteApiAppBrandByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppBrandSetProductTypeData = {
    body?: IczpNet_Invoicing_Brands_Dtos_BrandSetProductTypeInput;
};

export type PostApiAppBrandSetProductTypeResponse = (unknown);

export type PostApiAppBrandSetProductTypeError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppBrandManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppBrandManyResponse = (Array<IczpNet_Invoicing_Brands_Dtos_BrandDetailDto>);

export type GetApiAppBrandManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppBrandManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppBrandManyResponse = (unknown);

export type DeleteApiAppBrandManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductCategoryByIdItemByCacheData = {
    path: {
        id: string;
    };
};

export type GetApiAppProductCategoryByIdItemByCacheResponse = (IczpNet_Invoicing_ProductCategorys_ProductCategoryInfo);

export type GetApiAppProductCategoryByIdItemByCacheError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductCategoryManayByCacheData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppProductCategoryManayByCacheResponse = (Array<IczpNet_Invoicing_ProductCategorys_ProductCategoryInfo>);

export type GetApiAppProductCategoryManayByCacheError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductCategoryByCacheData = {
    query?: {
        DepthList?: Array<(number)>;
        IsEnabledParentId?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        ParentId?: string;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppProductCategoryByCacheResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppProductCategoryByCacheError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductCategoryByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppProductCategoryByIdResponse = (IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDetailDto);

export type GetApiAppProductCategoryByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiAppProductCategoryByIdData = {
    body?: IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryUpdateInput;
    path: {
        id: string;
    };
};

export type PutApiAppProductCategoryByIdResponse = (IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDetailDto);

export type PutApiAppProductCategoryByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppProductCategoryByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppProductCategoryByIdResponse = (unknown);

export type DeleteApiAppProductCategoryByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductCategoryManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppProductCategoryManyResponse = (Array<IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDetailDto>);

export type GetApiAppProductCategoryManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppProductCategoryManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppProductCategoryManyResponse = (unknown);

export type DeleteApiAppProductCategoryManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductCategoryData = {
    query?: {
        DepthList?: Array<(number)>;
        IsActive?: boolean;
        IsEnabledParentId?: boolean;
        IsStatic?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        ParentId?: string;
        ShopId?: string;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppProductCategoryResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppProductCategoryError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppProductCategoryData = {
    body?: IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryCreateInput;
};

export type PostApiAppProductCategoryResponse = (IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDetailDto);

export type PostApiAppProductCategoryError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppProductCategoryRepairDataData = {
    query?: {
        maxResultCount?: number;
        skinCount?: number;
        sorting?: string;
    };
};

export type PostApiAppProductCategoryRepairDataResponse = (string);

export type PostApiAppProductCategoryRepairDataError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductCategoryByIdRootChildrenData = {
    path: {
        id: string;
    };
};

export type GetApiAppProductCategoryByIdRootChildrenResponse = (Array<IczpNet_Invoicing_ProductCategorys_Dtos_ProductCategoryDetailDto>);

export type GetApiAppProductCategoryByIdRootChildrenError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppProductTypeData = {
    body?: IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeCreateInput;
};

export type PostApiAppProductTypeResponse = (IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDetailDto);

export type PostApiAppProductTypeError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeData = {
    query?: {
        BrandId?: string;
        CategoryId?: string;
        IsActive?: boolean;
        IsImprotChilds?: boolean;
        IsStatic?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppProductTypeResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppProductTypeError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiAppProductTypeByIdData = {
    body?: IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeUpdateInput;
    path: {
        id: string;
    };
};

export type PutApiAppProductTypeByIdResponse = (IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDetailDto);

export type PutApiAppProductTypeByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppProductTypeByIdResponse = (IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDetailDto);

export type GetApiAppProductTypeByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppProductTypeByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppProductTypeByIdResponse = (unknown);

export type DeleteApiAppProductTypeByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppProductTypeSetPropertyNamesByProductTypeIdData = {
    body?: {
        [key: string]: IczpNet_Invoicing_ProductTypes_Dtos_ProductTypePropertyNameInput;
    };
    path: {
        productTypeId: string;
    };
};

export type PostApiAppProductTypeSetPropertyNamesByProductTypeIdResponse = ({
    [key: string]: IczpNet_Invoicing_ProductTypes_Dtos_ProductTypePropertyNameInput;
});

export type PostApiAppProductTypeSetPropertyNamesByProductTypeIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypePropertyNameListByProductTypeIdData = {
    path: {
        productTypeId: string;
    };
};

export type GetApiAppProductTypePropertyNameListByProductTypeIdResponse = (Array<IczpNet_Invoicing_ProductTypes_Dtos_ProductTypePropertyNameDto>);

export type GetApiAppProductTypePropertyNameListByProductTypeIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypePropertyNamesByProductTypeIdData = {
    path: {
        productTypeId: string;
    };
};

export type GetApiAppProductTypePropertyNamesByProductTypeIdResponse = ({
    [key: string]: IczpNet_Invoicing_ProductTypes_Dtos_ProductTypePropertyNameInput;
});

export type GetApiAppProductTypePropertyNamesByProductTypeIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppProductTypeManyResponse = (Array<IczpNet_Invoicing_ProductTypes_Dtos_ProductTypeDetailDto>);

export type GetApiAppProductTypeManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppProductTypeManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppProductTypeManyResponse = (unknown);

export type DeleteApiAppProductTypeManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeCategoryByIdItemByCacheData = {
    path: {
        id: string;
    };
};

export type GetApiAppProductTypeCategoryByIdItemByCacheResponse = (IczpNet_Invoicing_ProductTypeCategorys_ProductTypeCategoryInfo);

export type GetApiAppProductTypeCategoryByIdItemByCacheError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeCategoryManayByCacheData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppProductTypeCategoryManayByCacheResponse = (Array<IczpNet_Invoicing_ProductTypeCategorys_ProductTypeCategoryInfo>);

export type GetApiAppProductTypeCategoryManayByCacheError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeCategoryByCacheData = {
    query?: {
        DepthList?: Array<(number)>;
        IsEnabledParentId?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        ParentId?: string;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppProductTypeCategoryByCacheResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppProductTypeCategoryByCacheError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeCategoryByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppProductTypeCategoryByIdResponse = (IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDetailDto);

export type GetApiAppProductTypeCategoryByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiAppProductTypeCategoryByIdData = {
    body?: IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryUpdateInput;
    path: {
        id: string;
    };
};

export type PutApiAppProductTypeCategoryByIdResponse = (IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDetailDto);

export type PutApiAppProductTypeCategoryByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppProductTypeCategoryByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppProductTypeCategoryByIdResponse = (unknown);

export type DeleteApiAppProductTypeCategoryByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeCategoryManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppProductTypeCategoryManyResponse = (Array<IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDetailDto>);

export type GetApiAppProductTypeCategoryManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppProductTypeCategoryManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppProductTypeCategoryManyResponse = (unknown);

export type DeleteApiAppProductTypeCategoryManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeCategoryData = {
    query?: {
        DepthList?: Array<(number)>;
        IsActive?: boolean;
        IsEnabledParentId?: boolean;
        IsStatic?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        ParentId?: string;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppProductTypeCategoryResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppProductTypeCategoryError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppProductTypeCategoryData = {
    body?: IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryCreateInput;
};

export type PostApiAppProductTypeCategoryResponse = (IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDetailDto);

export type PostApiAppProductTypeCategoryError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppProductTypeCategoryRepairDataData = {
    query?: {
        maxResultCount?: number;
        skinCount?: number;
        sorting?: string;
    };
};

export type PostApiAppProductTypeCategoryRepairDataResponse = (string);

export type PostApiAppProductTypeCategoryRepairDataError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppProductTypeCategoryByIdRootChildrenData = {
    path: {
        id: string;
    };
};

export type GetApiAppProductTypeCategoryByIdRootChildrenResponse = (Array<IczpNet_Invoicing_ProductTypeCategorys_Dtos_ProductTypeCategoryDetailDto>);

export type GetApiAppProductTypeCategoryByIdRootChildrenError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppPropertyNameByProductTypeByProductTypeIdData = {
    body?: IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameCreateInput;
    path: {
        productTypeId: string;
    };
};

export type PostApiAppPropertyNameByProductTypeByProductTypeIdResponse = (IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameDto);

export type PostApiAppPropertyNameByProductTypeByProductTypeIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppPropertyNameByProductTypeByProductTypeIdData = {
    path: {
        productTypeId: string;
    };
    query?: {
        isActive?: boolean;
    };
};

export type GetApiAppPropertyNameByProductTypeByProductTypeIdResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppPropertyNameByProductTypeByProductTypeIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppPropertyNameByIdUpdateData = {
    body?: IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameUpdateInput;
    path: {
        id: string;
    };
};

export type PostApiAppPropertyNameByIdUpdateResponse = (IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameDto);

export type PostApiAppPropertyNameByIdUpdateError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppPropertyNameData = {
    query?: {
        IdList?: Array<(string)>;
        IsActive?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        ProductTypeId?: string;
        SkipCount?: number;
        Sorting?: string;
        StandardProductUnitId?: string;
        ValueType?: IczpNet_Invoicing_Enums_ValueTypeEnum;
    };
};

export type GetApiAppPropertyNameResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppPropertyNameError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppPropertyNameByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppPropertyNameByIdResponse = (IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameDto);

export type GetApiAppPropertyNameByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppPropertyNameByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppPropertyNameByIdResponse = (unknown);

export type DeleteApiAppPropertyNameByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppPropertyNameManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppPropertyNameManyResponse = (Array<IczpNet_Invoicing_PropertyNames_Dtos_PropertyNameDto>);

export type GetApiAppPropertyNameManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppPropertyNameManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppPropertyNameManyResponse = (unknown);

export type DeleteApiAppPropertyNameManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppPropertyValueData = {
    body?: IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueCreateInput;
};

export type PostApiAppPropertyValueResponse = (IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueDto);

export type PostApiAppPropertyValueError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppPropertyValueData = {
    query?: {
        IsActive?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        PropertyNameId?: string;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppPropertyValueResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppPropertyValueError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppPropertyValueByIdUpdateData = {
    body?: IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueUpdateInput;
    path: {
        id: string;
    };
};

export type PostApiAppPropertyValueByIdUpdateResponse = (IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueDto);

export type PostApiAppPropertyValueByIdUpdateError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppPropertyValueByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppPropertyValueByIdResponse = (IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueDto);

export type GetApiAppPropertyValueByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppPropertyValueByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppPropertyValueByIdResponse = (unknown);

export type DeleteApiAppPropertyValueByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppPropertyValueManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppPropertyValueManyResponse = (Array<IczpNet_Invoicing_PropertyValues_Dtos_PropertyValueDto>);

export type GetApiAppPropertyValueManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppPropertyValueManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppPropertyValueManyResponse = (unknown);

export type DeleteApiAppPropertyValueManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppStandardProductUnitData = {
    body?: IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitCreateInput;
};

export type PostApiAppStandardProductUnitResponse = (IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDetailDto);

export type PostApiAppStandardProductUnitError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppStandardProductUnitData = {
    query?: {
        BrandIdList?: Array<(string)>;
        Fields?: Array<(string)>;
        Filters?: Array<IczpNet_AbpCommons_Models_FilterInput>;
        IsActive?: boolean;
        IsImportChildsProductCategory?: boolean;
        IsInStock?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        PriceRangeEnd?: number;
        PriceRangeStart?: number;
        ProductCategoryIdList?: Array<(string)>;
        ProductTypeId?: string;
        ShopId?: string;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiAppStandardProductUnitResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppStandardProductUnitError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiAppStandardProductUnitByIdData = {
    body?: IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitUpdateInput;
    path: {
        id: string;
    };
};

export type PutApiAppStandardProductUnitByIdResponse = (IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDetailDto);

export type PutApiAppStandardProductUnitByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppStandardProductUnitByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppStandardProductUnitByIdResponse = (IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDetailDto);

export type GetApiAppStandardProductUnitByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppStandardProductUnitByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppStandardProductUnitByIdResponse = (unknown);

export type DeleteApiAppStandardProductUnitByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppStandardProductUnitSetPropertyValueByStandardProductUnitIdData = {
    body?: Array<(string)>;
    path: {
        standardProductUnitId: string;
    };
};

export type PostApiAppStandardProductUnitSetPropertyValueByStandardProductUnitIdResponse = (unknown);

export type PostApiAppStandardProductUnitSetPropertyValueByStandardProductUnitIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppStandardProductUnitSetManyCategoryListData = {
    body?: {
        [key: string]: Array<(string)>;
    };
};

export type PostApiAppStandardProductUnitSetManyCategoryListResponse = (unknown);

export type PostApiAppStandardProductUnitSetManyCategoryListError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppStandardProductUnitSetCategoryListByStandardProductUnitIdData = {
    body?: Array<(string)>;
    path: {
        standardProductUnitId: string;
    };
};

export type PostApiAppStandardProductUnitSetCategoryListByStandardProductUnitIdResponse = (unknown);

export type PostApiAppStandardProductUnitSetCategoryListByStandardProductUnitIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppStandardProductUnitManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppStandardProductUnitManyResponse = (Array<IczpNet_Invoicing_StandardProductUnits_Dtos_StandardProductUnitDetailDto>);

export type GetApiAppStandardProductUnitManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppStandardProductUnitManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppStandardProductUnitManyResponse = (unknown);

export type DeleteApiAppStandardProductUnitManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppStockKeepingUnitData = {
    body?: IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitCreateInput;
};

export type PostApiAppStockKeepingUnitResponse = (IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDto);

export type PostApiAppStockKeepingUnitError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppStockKeepingUnitData = {
    query?: {
        IsActive?: boolean;
        Keyword?: string;
        MaxResultCount?: number;
        ShopId?: string;
        SkipCount?: number;
        Sorting?: string;
        StandardProductUnitId?: string;
    };
};

export type GetApiAppStockKeepingUnitResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppStockKeepingUnitError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppStockKeepingUnitByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAppStockKeepingUnitByIdResponse = (IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDto);

export type GetApiAppStockKeepingUnitByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiAppStockKeepingUnitByIdData = {
    body?: IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitUpdateInput;
    path: {
        id: string;
    };
};

export type PutApiAppStockKeepingUnitByIdResponse = (IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDto);

export type PutApiAppStockKeepingUnitByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppStockKeepingUnitByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiAppStockKeepingUnitByIdResponse = (unknown);

export type DeleteApiAppStockKeepingUnitByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppStockKeepingUnitByIdDetailData = {
    path: {
        id: string;
    };
};

export type GetApiAppStockKeepingUnitByIdDetailResponse = (IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDetailDto);

export type GetApiAppStockKeepingUnitByIdDetailError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppStockKeepingUnitManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type GetApiAppStockKeepingUnitManyResponse = (Array<IczpNet_Invoicing_StockKeepingUnits_Dtos_StockKeepingUnitDto>);

export type GetApiAppStockKeepingUnitManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiAppStockKeepingUnitManyData = {
    query?: {
        idList?: Array<(string)>;
    };
};

export type DeleteApiAppStockKeepingUnitManyResponse = (unknown);

export type DeleteApiAppStockKeepingUnitManyError = (Volo_Abp_Http_RemoteServiceErrorResponse);