# version: '3.4'

services:
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server
  #   volumes:
  #     - dbdata:/var/opt/mssql
  
  auth-server:
    image: iczpnet/chat-auth-server:v0.0.3-beta
    build:
      # context: ../../
      dockerfile: host/IczpNet.Chat.AuthServer/Dockerfile
    # depends_on:
    #   - sqlserver      
  
  chat:
    image: iczpnet/chat-api-host:v0.0.3-beta
    build:
      # context: ../../
      dockerfile: host/IczpNet.Chat.HttpApi.Host/Dockerfile
    depends_on:
      # - sqlserver
      - auth-server

# volumes:
#   dbdata: F:\Dev\Docker\Volumes\ChatDb